# Generated by Django 4.2.4 on 2023-08-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(verbose_name='Form Version')),
                ('definition', models.JSONField(verbose_name='Form Definition')),
                ('translations', models.JSONField()),
                ('default_lang_code', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned'), ('archived', 'Archived'), ('rejected', 'Rejected'), ('pending_approval', 'Pending Approval'), ('deleted', 'Deleted')], max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='forms_service.formdefinition')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
