# Generated by Django 4.2.4 on 2023-08-20 20:11

from django.conf import settings
from django.db import migrations
from .. import conf


def create_google_social_app(apps, schema_editor):
    
    client_id = conf.GOOGLE_CLIENT_ID
    secret_key = conf.GOOGLE_SECRET_KEY
    
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    Site = apps.get_model('sites', 'Site')
    Site.objects.get_or_create(domain=settings.DOMAIN,defaults = {'name':settings.DEFAULT_NAME})
    site = Site.objects.get_current()
    google_app, created = SocialApp.objects.get_or_create(
        provider='google',
        name='Google',
        client_id=client_id,
        secret=secret_key,
    )
    if created:
        google_app.sites.add(site)
        google_app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users_service','0001_initial'),
        ('sites', '0001_initial'),  # Initial migration for the sites app
        ('socialaccount', '0001_initial'), # Initial migration for the socialaccount app
    ]

    operations = [
        migrations.RunPython(create_google_social_app),
    ]