# Generated by Django 4.2.4 on 2023-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0002_auto_20230820_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=12),
        ),
    ]
